version: '3'

tasks:
  build:
    cmds:
    - docker build --tag peer .
  run-1:
    cmds:
    - docker run -it --name peer-1 --network poc-p2p peer
  run-2:
    cmds:
    - docker run -it --name peer-2 --network poc-p2p peer

